// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebChatMessagePart } from "./WebChatMessagePart";

export type SubmitTextRequest = { sender_id: string, text: string, image_urls: Array<string>, message_parts: Array<WebChatMessagePart>, };
