// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebChatMessagePart = { "type": "plain", text: string, } | { "type": "image", url: string, } | { "type": "reply", message_id: string, selected_text: string, } | { "type": "record", url: string, } | { "type": "video", url: string, } | { "type": "file", name: string, url: string, };
