[package]
name = "astrbot-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
astrbot-platform = { path = "../astrbot-platform" }
astrbot-runtime = { path = "../astrbot-runtime" }
astrbot-web = { path = "../astrbot-web" }
tokio.workspace = true

[dev-dependencies]
reqwest.workspace = true
