[package]
name = "astrbot-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
astrbot-core = { path = "../astrbot-core" }
astrbot-tool = { path = "../astrbot-tool" }
async-trait.workspace = true
md5 = "0.7"
reqwest.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
wasmtime.workspace = true
zip.workspace = true

[dev-dependencies]
wat.workspace = true
