mod attachment;
mod dashboard;
mod dto;
mod error;
mod history;
mod management;
mod message_parts;
mod openapi;
mod realtime;
mod reference;
mod routes;
mod server;

pub use attachment::{AttachmentDescriptor, AttachmentService, PassthroughAttachmentService};
pub use dto::{
    ErrorResponse, SubmitTextRequest, SubmitTextResponse, WebChatMessagePart,
    WebChatMessageResponse, WebChatMessagesResponse,
};
pub use management::{
    ApiKeyAuthDecision, ApiKeyIssuer, ApiKeyRejectionReason, AuthRejectionReason,
    DashboardAccountEditRequest, DashboardAuthDecision, DashboardAuthPolicy, DashboardAuthResponse,
    DashboardCapabilitiesResponse, DashboardClosureLevel, DashboardLoginData,
    DashboardLoginRequest, DashboardServiceCapability, DashboardUpdatePlanRequest, FileUploadError,
    IssuedApiKey, LocalMaintenanceExecutor, MaintenanceChangelogResponse, MaintenanceCheckResponse,
    MaintenanceExecutionFuture, MaintenanceMigrationCheckResponse, MaintenanceMigrationExecutor,
    MaintenanceOperationResponse, MaintenanceOperationRunRequest, MaintenanceOperationsResponse,
    MaintenancePackageExecutor, MaintenancePackagePlanResponse, MaintenanceReleaseExecutor,
    MaintenanceRestartExecutor, MaintenanceRestartRequest, ManagementAbconfCatalogResponse,
    ManagementAbconfCreateRequest, ManagementAbconfCreateResponse, ManagementAbconfDeleteResponse,
    ManagementAbconfIdRequest, ManagementAbconfResponse, ManagementAbconfUpdateRequest,
    ManagementActor, ManagementApiKeyCatalogResponse, ManagementApiKeyDeleteRequest,
    ManagementApiKeyDeleteResponse, ManagementApiKeyDescriptor, ManagementApiKeyIssueRequest,
    ManagementApiKeyIssueResponse, ManagementApiKeyRevokeRequest, ManagementApiKeyRevokeResponse,
    ManagementApiKeyState, ManagementApiState, ManagementAuditEntry, ManagementAuditFileStore,
    ManagementAuthState, ManagementBackupAbortRequest, ManagementBackupAbortResponse,
    ManagementBackupChunkRequest, ManagementBackupChunkResponse, ManagementBackupCompleteRequest,
    ManagementBackupCompleteResponse, ManagementBackupExportRequest, ManagementBackupImportRequest,
    ManagementBackupJobResponse, ManagementBackupPrecheckRequest, ManagementBackupPrecheckResponse,
    ManagementBackupProgressCatalogResponse, ManagementBackupProgressResponse,
    ManagementBackupState, ManagementBackupUploadStartRequest, ManagementBackupUploadStartResponse,
    ManagementChatProjectActorRequest, ManagementChatProjectCatalogResponse,
    ManagementChatProjectCreateRequest, ManagementChatProjectDescriptor,
    ManagementChatProjectGetRequest, ManagementChatProjectMembershipRequest,
    ManagementChatProjectMutationResponse, ManagementChatProjectResponse,
    ManagementChatProjectSessionResponse, ManagementChatProjectSessionUpsertRequest,
    ManagementChatProjectSessionsResponse, ManagementChatProjectState,
    ManagementChatProjectUpdateRequest, ManagementChatProviderDescriptor,
    ManagementCommandCatalogResponse, ManagementCommandDescriptor,
    ManagementCommandMutationResponse, ManagementCommandUpdateRequest,
    ManagementConfigApplyExecution, ManagementConfigApplyExecutionRequest,
    ManagementConfigApplyExecutor, ManagementConfigApplyFuture, ManagementConfigApplyState,
    ManagementConfigCurrentResponse, ManagementConfigMutationRequest,
    ManagementConfigMutationResponse, ManagementConfigRouteCatalogResponse,
    ManagementConfigRouteDeleteRequest, ManagementConfigRouteMutationResponse,
    ManagementConfigRouteReplaceRequest, ManagementConfigRouteResolveRequest,
    ManagementConfigRouteResolveResponse, ManagementConfigRouteState,
    ManagementConfigRouteUpsertRequest, ManagementConfigSchemaResponse,
    ManagementConversationBatchDeleteRequest, ManagementConversationBatchDeleteResponse,
    ManagementConversationCatalogResponse, ManagementConversationCurrentRequest,
    ManagementConversationCurrentResponse, ManagementConversationDeleteRequest,
    ManagementConversationDeleteResponse, ManagementConversationDescriptor,
    ManagementConversationGetRequest, ManagementConversationListRequest,
    ManagementConversationMutationResponse, ManagementConversationRenameRequest,
    ManagementConversationResponse, ManagementConversationState,
    ManagementConversationUpsertRequest, ManagementCronCatalogResponse,
    ManagementCronDeleteResponse, ManagementCronJobRequest, ManagementCronListRequest,
    ManagementCronMutationResponse, ManagementCronState, ManagementCronTickRequest,
    ManagementCronTickResponse, ManagementCronUpsertRequest, ManagementFileDownloadState,
    ManagementFileUploadResponse, ManagementKnowledgeBaseCatalogResponse,
    ManagementKnowledgeBaseCreateRequest, ManagementKnowledgeBaseIdRequest,
    ManagementKnowledgeBaseResponse, ManagementKnowledgeBaseState,
    ManagementKnowledgeBaseUpdateRequest, ManagementKnowledgeChunkCatalogResponse,
    ManagementKnowledgeChunkDeleteRequest, ManagementKnowledgeDocumentCatalogResponse,
    ManagementKnowledgeDocumentIdRequest, ManagementKnowledgeIngestRequest,
    ManagementKnowledgeIngestResponse, ManagementKnowledgeMutationResponse,
    ManagementKnowledgePreflightResponse, ManagementKnowledgeProviderPreflightRequest,
    ManagementKnowledgeUploadCompleteRequest, ManagementKnowledgeUploadFailRequest,
    ManagementKnowledgeUploadPlanRequest, ManagementKnowledgeUploadProgressRequest,
    ManagementKnowledgeUploadTaskResponse, ManagementLogQuery, ManagementLogResponse,
    ManagementMaintenanceState, ManagementMcpCatalogResponse, ManagementMcpCheckRequest,
    ManagementMcpCheckResponse, ManagementMcpDeleteRequest, ManagementMcpMutationResponse,
    ManagementMcpServerConfigView, ManagementMcpServerDescriptor, ManagementMcpState,
    ManagementMcpSyncRequest, ManagementMcpSyncResponse, ManagementMcpUpsertRequest,
    ManagementMetricFileStore, ManagementObservabilityState, ManagementPersonaCatalogResponse,
    ManagementPersonaFolderUpsertRequest, ManagementPersonaListRequest,
    ManagementPersonaMutationResponse, ManagementPersonaResolveRequest,
    ManagementPersonaResolveResponse, ManagementPersonaState, ManagementPersonaUpsertRequest,
    ManagementPlatformCatalogResponse, ManagementPlatformCheckRequest,
    ManagementPlatformCheckResponse, ManagementPlatformDeleteRequest, ManagementPlatformDescriptor,
    ManagementPlatformHealthCheck, ManagementPlatformHealthFuture, ManagementPlatformHealthResult,
    ManagementPlatformMutationResponse, ManagementPlatformSessionDescriptor,
    ManagementPlatformStatsSummary, ManagementPlatformTemplate, ManagementPlatformUpsertRequest,
    ManagementPluginAction, ManagementPluginConfigFileDeleteResponse,
    ManagementPluginConfigFileDescriptor, ManagementPluginConfigFileListRequest,
    ManagementPluginConfigFileListResponse, ManagementPluginConfigFileReadResponse,
    ManagementPluginConfigFileRequest, ManagementPluginConfigFileWriteRequest,
    ManagementPluginConfigFileWriteResponse, ManagementPluginConfigRequest,
    ManagementPluginDescriptor, ManagementPluginLifecycleActionRequest,
    ManagementPluginLifecycleCatalogResponse, ManagementPluginLifecycleEventDescriptor,
    ManagementPluginLifecycleMutationResponse, ManagementPluginLifecycleState,
    ManagementPluginOperationRecord, ManagementPluginSeed, ManagementPluginSourceDescriptor,
    ManagementPluginSourcePlanRequest, ManagementPluginSourcePlanResponse,
    ManagementPluginUploadPlanRequest, ManagementPluginUploadPlanResponse,
    ManagementProviderCatalogResponse, ManagementProviderCheckRequest,
    ManagementProviderCheckResponse, ManagementProviderDeleteRequest,
    ManagementProviderHealthCheck, ManagementProviderHealthFuture, ManagementProviderHealthResult,
    ManagementProviderModelsFuture, ManagementProviderModelsRequest,
    ManagementProviderModelsResponse, ManagementProviderModelsResult,
    ManagementProviderMutationResponse, ManagementProviderTemplate,
    ManagementProviderUpsertRequest, ManagementProviderUsageSummary,
    ManagementRuntimeConfigApplyController, ManagementSessionRuleState,
    ManagementSkillActivationRequest, ManagementSkillActivationResponse,
    ManagementSkillCatalogResponse, ManagementSkillDeletePlanRequest,
    ManagementSkillDeletePlanResponse, ManagementSkillDeleteResponse, ManagementSkillDescriptor,
    ManagementSkillInstallPlanRequest, ManagementSkillInstallPlanResponse,
    ManagementSkillInstallResponse, ManagementSkillState, ManagementStatsResponse,
    ManagementStatusResponse, ManagementSubagentApplyRequest, ManagementSubagentApplyResponse,
    ManagementSubagentCatalogResponse, ManagementSubagentConfig, ManagementSubagentDescriptor,
    ManagementSubagentExecuteRequest, ManagementSubagentExecuteResponse,
    ManagementSubagentExecutionBridge, ManagementSubagentExecutionRecord,
    ManagementSubagentExecutionResult, ManagementSubagentHandoffDescriptor,
    ManagementSubagentState, ManagementToolCatalogResponse, ManagementToolDescriptor,
    ManagementToolState, ManagementToolToggleRequest, ManagementToolToggleResponse,
    ManagementTraceResponse, OpenApiScope, OpenApiScopeSet, PlatformManagementResponse,
    PluginHandlerManagementResponse, PluginManagementResponse, PluginMarketCatalogResponse,
    PluginMarketExecuteResponse, PluginMarketInstalledPlugin, PluginMarketManagementState,
    PluginMarketOperationRecord, PluginMarketOperationStatus, PluginMarketPlanRequest,
    PluginMarketPlanResponse, PluginMarketPluginDescriptor, PluginMarketUpdateAllExecuteResponse,
    PluginMarketUpdateAllPlanResponse, PluginMarketUpdateAllRequest, PresentedApiKey,
    ProjectUpdatePlanRequest, ProviderManagementResponse, ScopedDownloadError, ScopedDownloadFile,
    authorize_api_key, extract_bearer_token, extract_presented_api_key, hash_api_key,
    management_router, management_router_with_auth,
};
pub use openapi::{
    OpenApiChatHttpResponse, OpenApiChatHttpSubscription, openapi_chat_router,
    openapi_chat_router_with_realtime,
};
pub use realtime::{
    DEFAULT_LIVE_AUDIO_FORMAT, LiveAudioBuffer, LiveAudioError, LiveAudioFormat, LiveAudioWavFile,
    OpenApiChatAuthContext, OpenApiChatEnqueuePlan, OpenApiChatGateway, OpenApiChatGatewayError,
    OpenApiChatGatewayRequest, OpenApiChatMessagePart, OpenApiChatMessageRequest,
    OpenApiChatResponseMode, OpenApiChatSubscriptionPlan, RealtimeChatSubscriptionRecord,
    RealtimeChatSubscriptionStatus, RealtimeConnectionSession, RealtimeControlState,
    RealtimeElicitationCatalogResponse, RealtimeElicitationCreateRequest,
    RealtimeElicitationRecord, RealtimeElicitationRespondRequest, RealtimeElicitationStatus,
    RealtimeProcessingState, RealtimeStopRequest, RealtimeStopResponse, RealtimeSubscription,
    RealtimeSubscriptionCatalogResponse, required_openapi_chat_scopes,
};
pub use reference::{WebChatReferenceItem, WebChatReferenceResponse};
pub use routes::webchat_router;
pub use server::{
    dashboard_router, dashboard_router_with_auth, serve_dashboard,
    serve_dashboard_with_auth_and_shutdown, serve_dashboard_with_shutdown, serve_management,
    serve_management_with_auth, serve_management_with_auth_and_shutdown,
    serve_management_with_shutdown, serve_webchat, serve_webchat_with_shutdown,
};

#[cfg(test)]
mod tests;
